import Head from 'next/head';
import Image from 'next/image';

import DefaultLayout from '@/layouts/DefaultLayout';
import notFound from '../assets/svg/404.svg';

export default function Custom404() {
	return (
		<>
			<Head>
				<title>Sproutify | Not found</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<DefaultLayout>
				<div className="flex  w-screen flex-col items-center justify-center py-20">
					<h2 className="font-sans text-[120px] font-semibold leading-[146px]">
						Ooops!
					</h2>

					<Image src={notFound} alt="" />
				</div>
			</DefaultLayout>
		</>
	);
}
